judge_model: gpt-4.1
temperature: 0.0
max_tokens: 16000

bench_name: arena-hard-v2.0
reference: null

answer_dir: data/arena-hard-v2.0/model_answer
baseline_answer_dir: archive/data/arena-hard-v2.0/model_answer
judgment_output_dir: data/arena-hard-v2.0/model_judgment/gpt-4.1

regex_patterns:
  - \[\[([AB<>=]+)\]\]
  - \[([AB<>=]+)\]

prompt_template: "<|User Prompt|>\n{QUESTION}\n\n<|The Start of Assistant A's Answer|>\n{ANSWER_A}\n<|The End of Assistant A's Answer|>\n\n<|The Start of Assistant B's Answer|>\n{ANSWER_B}\n<|The End of Assistant B's Answer|>"

model_list:
  - gemma_2_9b_it_simpo
  - gemma_2_9b_it_dpo
  - llama_3_base_8b_sft_ipo
  - llama_3_base_8b_sft_dpo
  - llama_3_base_8b_sft_kto
  - llama_3_base_8b_sft_orpo
  - llama_3_base_8b_sft_rdpo
  - llama_3_base_8b_sft_simpo
  - llama_3_base_8b_sft
  - llama_3_instruct_8b_simpo
  - llama_3_instruct_8b_ipo
  - llama_3_instruct_8b_kto
  - llama_3_instruct_8b_orpo
  - llama_3_instruct_8b_rdpo
  - llama_3_instruct_8b_dpo
  - mistral_7b_instruct_rdpo
  - mistral_7b_instruct_dpo
  - mistral_7b_instruct_ipo
  - mistral_7b_instruct_kto
  - mistral_7b_instruct_simpo
  - mistral_7b_instruct_orpo
  - mistral_7b_base_sft_ipo
  - mistral_7b_base_sft_kto
  - mistral_7b_base_sft_dpo
  - mistral_7b_base_sft_rdpo
  - mistral_7b_base_sft_simpo
  - mistral_7b_base_sft_cpo
  - mistral_7b_base_sft_rrhf
  - mistral_7b_base_sft_slic_hf
  - mistral_7b_instruct_cpo
  - mistral_7b_instruct_rrhf
  - mistral_7b_instruct_slic_hf
  - llama_3_base_8b_sft_cpo
  - llama_3_base_8b_sft_rrhf
  - llama_3_base_8b_sft_slic_hf
  - llama_3_instruct_8b_cpo
  - llama_3_instruct_8b_rrhf
  - llama_3_instruct_8b_slic_hf
  - llama_3_instruct_8b_rrhf_v0_2
  - llama_3_instruct_8b_slic_hf_v0_2
  - llama_3_instruct_8b_dpo_v0_2
  - llama_3_instruct_8b_ipo_v0_2
  - llama_3_instruct_8b_cpo_v0_2
  - llama_3_instruct_8b_kto_v0_2
  - llama_3_instruct_8b_orpo_v0_2
  - llama_3_instruct_8b_rdpo_v0_2
  - llama_3_instruct_8b_simpo_v0_2
